### ISSUE TITLE
Server

### ISSUE THREAD

**Issue by Steve-the-Skunk** [vinceh121/Minegasm-fabric#6]
The mod does not work on servers. I use the Lovence Hush 2 device. Everything worked fine on the Forge version. It works alone and on a local network on this port. But it doesn't work on the server of some public.

**Comment by vinceh121** [comment]
Release [v2.1.2-1.20.1](https://github.com/vinceh121/Minegasm-fabric/releases/tag/v2.1.2-1.20.1) fixes some problems with event hook-ins that didn't work on a remote server.
